pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('Build') {
      steps {
        echo "Build image"
      }
    }
    stage('Deploy') {
      parallel{
        stage('Pre-Deploy'){
          steps {
            sh 'sleep 5s'
            echo "Deploy application"
          }
        }
        stage('Post-Deploy'){
          steps{
            echo "Jenkins pipeline ended"
          }
        }
      }
    }
  }
}
